---
version: "3.4"
services:
  postgres-golang-learning:
    image: postgres:alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: postgres-golang-learning

  redis-golang-learning:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    container_name: redis-golang-learning
