---
logger:
  output:
    - stdout
  error:
    - stderr
  level: info
  encoding: json
db:
  path: user=postgres password=postgres dbname=postgres sslmode=disable
  type: in-memory
server:
  host: localhost
  port: 8080
test:
  doNotRemoveMe: 42
