---
logger:
  output:
    - stdout
  error:
    - stderr
  level: info
  encoding: json
db:
  path: user=postgres password=postgres dbname=postgres sslmode=disable
  type: sql
server:
  host: localhost
  httpPort: 8080
  grpcPort: 9090
test:
  doNotRemoveMe: 42
