// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package server

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BannerClient is the client API for Banner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BannerClient interface {
	// Banner methods.
	CreateBanner(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ReadBanners(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error)
	UpdateBanner(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteBanner(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error)
	// Slots methods.
	CreateSlot(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ReadSlots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error)
	UpdateSlot(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteSlot(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error)
	// Group methods.
	CreateGroup(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	ReadGroups(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error)
	UpdateGroup(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	DeleteGroup(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error)
	// Placement methods.
	CreatePlacement(ctx context.Context, in *PlacementCreateRequest, opts ...grpc.CallOption) (*PlacementIDsResponse, error)
	ReadPlacements(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultiplePlacementResponse, error)
	UpdatePlacement(ctx context.Context, in *PlacementUpdateRequest, opts ...grpc.CallOption) (*PlacementIDsResponse, error)
	DeletePlacement(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error)
	// Banner events methods.
	BannerShow(ctx context.Context, in *BannerShowRequest, opts ...grpc.CallOption) (*PlacementResponse, error)
	// pid is PlacementID.
	BannerClick(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error)
}

type bannerClient struct {
	cc grpc.ClientConnInterface
}

func NewBannerClient(cc grpc.ClientConnInterface) BannerClient {
	return &bannerClient{cc}
}

func (c *bannerClient) CreateBanner(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/CreateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) ReadBanners(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error) {
	out := new(MultipleSimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/ReadBanners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) UpdateBanner(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/UpdateBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) DeleteBanner(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error) {
	out := new(SimpleResponseID)
	err := c.cc.Invoke(ctx, "/server.Banner/DeleteBanner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) CreateSlot(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/CreateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) ReadSlots(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error) {
	out := new(MultipleSimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/ReadSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) UpdateSlot(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/UpdateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) DeleteSlot(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error) {
	out := new(SimpleResponseID)
	err := c.cc.Invoke(ctx, "/server.Banner/DeleteSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) CreateGroup(ctx context.Context, in *SimpleCreateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) ReadGroups(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultipleSimpleResponse, error) {
	out := new(MultipleSimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/ReadGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) UpdateGroup(ctx context.Context, in *SimpleUpdateRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/UpdateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) DeleteGroup(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error) {
	out := new(SimpleResponseID)
	err := c.cc.Invoke(ctx, "/server.Banner/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) CreatePlacement(ctx context.Context, in *PlacementCreateRequest, opts ...grpc.CallOption) (*PlacementIDsResponse, error) {
	out := new(PlacementIDsResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/CreatePlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) ReadPlacements(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*MultiplePlacementResponse, error) {
	out := new(MultiplePlacementResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/ReadPlacements", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) UpdatePlacement(ctx context.Context, in *PlacementUpdateRequest, opts ...grpc.CallOption) (*PlacementIDsResponse, error) {
	out := new(PlacementIDsResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/UpdatePlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) DeletePlacement(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error) {
	out := new(SimpleResponseID)
	err := c.cc.Invoke(ctx, "/server.Banner/DeletePlacement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) BannerShow(ctx context.Context, in *BannerShowRequest, opts ...grpc.CallOption) (*PlacementResponse, error) {
	out := new(PlacementResponse)
	err := c.cc.Invoke(ctx, "/server.Banner/BannerShow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bannerClient) BannerClick(ctx context.Context, in *SimpleRequestID, opts ...grpc.CallOption) (*SimpleResponseID, error) {
	out := new(SimpleResponseID)
	err := c.cc.Invoke(ctx, "/server.Banner/BannerClick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BannerServer is the server API for Banner service.
// All implementations should embed UnimplementedBannerServer
// for forward compatibility
type BannerServer interface {
	// Banner methods.
	CreateBanner(context.Context, *SimpleCreateRequest) (*SimpleResponse, error)
	ReadBanners(context.Context, *empty.Empty) (*MultipleSimpleResponse, error)
	UpdateBanner(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error)
	DeleteBanner(context.Context, *SimpleRequestID) (*SimpleResponseID, error)
	// Slots methods.
	CreateSlot(context.Context, *SimpleCreateRequest) (*SimpleResponse, error)
	ReadSlots(context.Context, *empty.Empty) (*MultipleSimpleResponse, error)
	UpdateSlot(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error)
	DeleteSlot(context.Context, *SimpleRequestID) (*SimpleResponseID, error)
	// Group methods.
	CreateGroup(context.Context, *SimpleCreateRequest) (*SimpleResponse, error)
	ReadGroups(context.Context, *empty.Empty) (*MultipleSimpleResponse, error)
	UpdateGroup(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error)
	DeleteGroup(context.Context, *SimpleRequestID) (*SimpleResponseID, error)
	// Placement methods.
	CreatePlacement(context.Context, *PlacementCreateRequest) (*PlacementIDsResponse, error)
	ReadPlacements(context.Context, *empty.Empty) (*MultiplePlacementResponse, error)
	UpdatePlacement(context.Context, *PlacementUpdateRequest) (*PlacementIDsResponse, error)
	DeletePlacement(context.Context, *SimpleRequestID) (*SimpleResponseID, error)
	// Banner events methods.
	BannerShow(context.Context, *BannerShowRequest) (*PlacementResponse, error)
	// pid is PlacementID.
	BannerClick(context.Context, *SimpleRequestID) (*SimpleResponseID, error)
}

// UnimplementedBannerServer should be embedded to have forward compatible implementations.
type UnimplementedBannerServer struct {
}

func (UnimplementedBannerServer) CreateBanner(context.Context, *SimpleCreateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBanner not implemented")
}
func (UnimplementedBannerServer) ReadBanners(context.Context, *empty.Empty) (*MultipleSimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBanners not implemented")
}
func (UnimplementedBannerServer) UpdateBanner(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBanner not implemented")
}
func (UnimplementedBannerServer) DeleteBanner(context.Context, *SimpleRequestID) (*SimpleResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBanner not implemented")
}
func (UnimplementedBannerServer) CreateSlot(context.Context, *SimpleCreateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedBannerServer) ReadSlots(context.Context, *empty.Empty) (*MultipleSimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadSlots not implemented")
}
func (UnimplementedBannerServer) UpdateSlot(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlot not implemented")
}
func (UnimplementedBannerServer) DeleteSlot(context.Context, *SimpleRequestID) (*SimpleResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSlot not implemented")
}
func (UnimplementedBannerServer) CreateGroup(context.Context, *SimpleCreateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedBannerServer) ReadGroups(context.Context, *empty.Empty) (*MultipleSimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadGroups not implemented")
}
func (UnimplementedBannerServer) UpdateGroup(context.Context, *SimpleUpdateRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedBannerServer) DeleteGroup(context.Context, *SimpleRequestID) (*SimpleResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedBannerServer) CreatePlacement(context.Context, *PlacementCreateRequest) (*PlacementIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlacement not implemented")
}
func (UnimplementedBannerServer) ReadPlacements(context.Context, *empty.Empty) (*MultiplePlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPlacements not implemented")
}
func (UnimplementedBannerServer) UpdatePlacement(context.Context, *PlacementUpdateRequest) (*PlacementIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlacement not implemented")
}
func (UnimplementedBannerServer) DeletePlacement(context.Context, *SimpleRequestID) (*SimpleResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlacement not implemented")
}
func (UnimplementedBannerServer) BannerShow(context.Context, *BannerShowRequest) (*PlacementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BannerShow not implemented")
}
func (UnimplementedBannerServer) BannerClick(context.Context, *SimpleRequestID) (*SimpleResponseID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BannerClick not implemented")
}

// UnsafeBannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BannerServer will
// result in compilation errors.
type UnsafeBannerServer interface {
	mustEmbedUnimplementedBannerServer()
}

func RegisterBannerServer(s *grpc.Server, srv BannerServer) {
	s.RegisterService(&_Banner_serviceDesc, srv)
}

func _Banner_CreateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).CreateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/CreateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).CreateBanner(ctx, req.(*SimpleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_ReadBanners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).ReadBanners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/ReadBanners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).ReadBanners(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_UpdateBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).UpdateBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/UpdateBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).UpdateBanner(ctx, req.(*SimpleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_DeleteBanner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).DeleteBanner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/DeleteBanner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).DeleteBanner(ctx, req.(*SimpleRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/CreateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).CreateSlot(ctx, req.(*SimpleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_ReadSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).ReadSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/ReadSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).ReadSlots(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_UpdateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).UpdateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/UpdateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).UpdateSlot(ctx, req.(*SimpleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_DeleteSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).DeleteSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/DeleteSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).DeleteSlot(ctx, req.(*SimpleRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).CreateGroup(ctx, req.(*SimpleCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_ReadGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).ReadGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/ReadGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).ReadGroups(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/UpdateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).UpdateGroup(ctx, req.(*SimpleUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).DeleteGroup(ctx, req.(*SimpleRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_CreatePlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacementCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).CreatePlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/CreatePlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).CreatePlacement(ctx, req.(*PlacementCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_ReadPlacements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).ReadPlacements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/ReadPlacements",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).ReadPlacements(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_UpdatePlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlacementUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).UpdatePlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/UpdatePlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).UpdatePlacement(ctx, req.(*PlacementUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_DeletePlacement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).DeletePlacement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/DeletePlacement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).DeletePlacement(ctx, req.(*SimpleRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_BannerShow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BannerShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).BannerShow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/BannerShow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).BannerShow(ctx, req.(*BannerShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Banner_BannerClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequestID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BannerServer).BannerClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.Banner/BannerClick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BannerServer).BannerClick(ctx, req.(*SimpleRequestID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Banner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.Banner",
	HandlerType: (*BannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBanner",
			Handler:    _Banner_CreateBanner_Handler,
		},
		{
			MethodName: "ReadBanners",
			Handler:    _Banner_ReadBanners_Handler,
		},
		{
			MethodName: "UpdateBanner",
			Handler:    _Banner_UpdateBanner_Handler,
		},
		{
			MethodName: "DeleteBanner",
			Handler:    _Banner_DeleteBanner_Handler,
		},
		{
			MethodName: "CreateSlot",
			Handler:    _Banner_CreateSlot_Handler,
		},
		{
			MethodName: "ReadSlots",
			Handler:    _Banner_ReadSlots_Handler,
		},
		{
			MethodName: "UpdateSlot",
			Handler:    _Banner_UpdateSlot_Handler,
		},
		{
			MethodName: "DeleteSlot",
			Handler:    _Banner_DeleteSlot_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Banner_CreateGroup_Handler,
		},
		{
			MethodName: "ReadGroups",
			Handler:    _Banner_ReadGroups_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Banner_UpdateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Banner_DeleteGroup_Handler,
		},
		{
			MethodName: "CreatePlacement",
			Handler:    _Banner_CreatePlacement_Handler,
		},
		{
			MethodName: "ReadPlacements",
			Handler:    _Banner_ReadPlacements_Handler,
		},
		{
			MethodName: "UpdatePlacement",
			Handler:    _Banner_UpdatePlacement_Handler,
		},
		{
			MethodName: "DeletePlacement",
			Handler:    _Banner_DeletePlacement_Handler,
		},
		{
			MethodName: "BannerShow",
			Handler:    _Banner_BannerShow_Handler,
		},
		{
			MethodName: "BannerClick",
			Handler:    _Banner_BannerClick_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/banner-api.proto",
}
