// generated by generate-grpc-methods; DO NOT EDIT
package server

import (
	"context"

	"github.com/ezhk/golang-learning/banners-rotation/internal/api"
	"github.com/ezhk/golang-learning/banners-rotation/internal/structs"
	"github.com/golang/protobuf/ptypes/empty"
	"google.golang.org/protobuf/types/known/timestamppb"
)

func ConvertSlotToSimpleResponse(b structs.Slot) *api.SimpleResponse {
	return &api.SimpleResponse{
		ID:          b.ID,
		Name:        b.Name,
		Description: b.Description,
		CreatedAt:   timestamppb.New(b.CreatedAt),
		UpdatedAt:   timestamppb.New(b.UpdatedAt),
	}
}

func ConvertSimpleUpdateRequestToSlot(r *api.SimpleUpdateRequest) structs.Slot {
	return structs.Slot{
		ID:          r.ID,
		Name:        r.Name,
		Description: r.Description,
	}
}

func (s Server) CreateSlot(ctx context.Context, r *api.SimpleCreateRequest) (*api.SimpleResponse, error) {
	slot, err := s.storage.CreateSlot(r.Name, r.Description)
	if err != nil {
		return nil, err
	}

	return ConvertSlotToSimpleResponse(slot), nil
}

func (s Server) ReadSlots(ctx context.Context, empty *empty.Empty) (*api.MultipleSimpleResponse, error) {
	slots, err := s.storage.ReadSlots()
	if err != nil {
		return nil, err
	}

	simpleResponses := make([]*api.SimpleResponse, 0)
	for _, slot := range slots {
		simpleResponses = append(simpleResponses, ConvertSlotToSimpleResponse(*slot))
	}

	return &api.MultipleSimpleResponse{Objects: simpleResponses}, nil
}

func (s Server) UpdateSlot(ctx context.Context, r *api.SimpleUpdateRequest) (*api.SimpleResponse, error) {
	slot := ConvertSimpleUpdateRequestToSlot(r)
	b, err := s.storage.UpdateSlot(slot)
	if err != nil {
		return nil, err
	}

	return ConvertSlotToSimpleResponse(b), nil
}

func (s Server) DeleteSlot(ctx context.Context, r *api.SimpleRequestID) (*api.SimpleResponseID, error) {
	if err := s.storage.DeleteSlot(r.ID); err != nil {
		return nil, err
	}

	return &api.SimpleResponseID{ID: r.ID}, nil
}
