// generated by generate-table-methods; DO NOT EDIT
package storage

import (
	"github.com/ezhk/golang-learning/banners-rotation/internal/exceptions"
	"github.com/ezhk/golang-learning/banners-rotation/internal/structs"
)

func (s *Storage) CreateSlot(slotName string) (structs.Slot, error) {
	slot := structs.Slot{Name: slotName}
	result := s.db.Create(&slot)

	return slot, result.Error
}

func (s *Storage) ReadSlots() ([]*structs.Slot, error) {
	slots := []*structs.Slot{}
	result := s.db.Find(&slots)

	return slots, result.Error
}

func (s *Storage) UpdateSlot(b structs.Slot) (structs.Slot, error) {
	slot := structs.Slot{ID: b.ID}
	result := s.db.Model(&slot).Updates(b)
	if result.RowsAffected < 1 {
		return slot, exceptions.ErrObjectNotExist
	}

	return slot, result.Error
}

func (s *Storage) DeleteSlot(id uint64) error {
	result := s.db.Delete(&structs.Slot{}, id)
	if result.RowsAffected < 1 {
		return exceptions.ErrNoChanges
	}

	return result.Error
}
