---
logger:
  output:
    - stdout_file
  error:
    - stderr
  level: info
  encoding: json
database:
  path: user=postgres password=postgres dbname=postgres sslmode=disable host=localhost port=5432
server:
  http: localhost:8080
  grpc: localhost:9090
